pre-commit:
  commands:
    check:
      glob: "src/*.{js,jsx}"
      run: npx @biomejs/biome check --write --no-errors-on-unmatched --files-ignore-unknown=true {staged_files} && git update-index --again